dist: trusty
language: java
jdk:
  - oraclejdk11
cache:
  directories:
    - $HOME/.m2
    - ./src/frontend/node_modules/
before_install:
  - npm install node
before_script:
  - npm install --prefix ./src/frontend/
script:
  - mvn clean test
  - npm run build --prefix ./src/frontend/