export const SAVE_ACTIVE_PROFILE = 'SAVE_ACTIVE_PROFILE'
export const LOADING_PROFILE = 'LOADING_PROFILE'

export const ADD_NEW_EDUCATION = 'ADD_NEW_EDUCATION'
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION'
export const DELETE_EDUCATION = 'DELETE_EDUCATION'

export const ADD_NEW_EXPERIENCE = 'ADD_NEW_EXPERIENCE'
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE'
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE'

export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION'
export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION'
export const DELETE_CERTIFICATION = 'DELETE_CERTIFICATION'