export const ADD_NEW_POST = 'ADD_NEW_POST'
export const LOADING_POSTS = 'LOADING_POSTS'
export const SAVE_POSTS = 'SAVE_POSTS'
export const UPDATE_POST = 'UPDATE_POST'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'