export const ADD_NEW_POST = 'ADD_NEW_POST'
export const USERS_WHO_LIKED_POST = 'SHOW_USERS_WHO_LIKED_POST'

export const ADD_EDUCATION = 'ADD_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'
export const EDIT_INTRO = 'EDIT_INTRO'

export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION'
export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION'
export const DELETE_CERTIFICATION = ' DELETE_CERTIFICATION'
