export const ADD_NEW_POST = 'ADD_NEW_POST'
export const USERS_WHO_LIKED_POST = 'SHOW_USERS_WHO_LIKED_POST'

export const EDIT_INTRO = 'EDIT_INTRO'

export const ADD_NEW_EDUCATION = 'ADD_NEW_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'

export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION'
export const EDIT_CERTIFICATION = 'EDIT_CERTIFICATION'
