export const ADD_NEW_POST = 'ADD_NEW_POST'
export const USERS_WHO_LIKED_POST = 'SHOW_USERS_WHO_LIKED_POST'
export const USERS_WHO_LIKED_COMMENT = 'SHOW_USERS_WHO_LIKED_COMMENT'

export const EDIT_INTRO = 'EDIT_INTRO'

export const ADD_NEW_EDUCATION = 'ADD_NEW_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'

export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION'
export const EDIT_CERTIFICATION = 'EDIT_CERTIFICATION'

export const ADD_BACKGROUND_PHOTO = 'ADD_BACKGROUND_PHOTO'

export const ADD_NEW_EXPERIENCE = 'ADD_NEW_EXPERIENCE'
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE'
