server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
spring:
  profiles:
    active: "local"
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 645730785365-1qk27l2efhkoanabkurvchdltk0f6trs.apps.googleusercontent.com
            clientSecret: yrfnMp5eHI-kUYlNVhknG4T5
            scope:
             - email
             - profile
jwt:
  header: Authorization
  secret: my-very-secret-key
