spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:linkedin"
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  data: data.sql
info:
  cloudinary:
    cloud-name: "dan-insta-step"
    api-key: "615942255258686"
    api-secret: "HnYwqnw7fBFrk9yn16CLt7r_s-I"