server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
spring:
  profiles:
    active: "local"
  servlet:
    multipart:
      max-file-size: 10000KB
      max-request-size: 10000KB
jwt:
  header: Authorization
  secret: my-very-secret-key

