drop table if exists connections cascade;

create table connections
(
    id            bigint generated by default as identity,
    created_date  timestamp,
    modified_date timestamp,
    user_who_id   bigint,
    user_whom_id  bigint,
    primary key (id)
);

ALTER TABLE connections
    ADD CONSTRAINT uq_connections UNIQUE (user_who_id, user_whom_id);