export const ADD_NEW_POST = 'ADD_NEW_POST'
export const SHOW_USERS_WHO_LIKED_POST = 'SHOW_USERS_WHO_LIKED_POST'
export const ADD_EDUCATION = 'ADD_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'