export const SAVE_INVITATIONS_FOR_ME = 'SAVE_INVITATIONS_FOR_ME'
export const SAVE_INVITATIONS_FROM_ME = 'SAVE_INVITATIONS_FROM_ME'
export const SAVE_FOLLOWED_AND_FOLLOWING = 'SAVE_FOLLOWED_AND_FOLLOWING'

export const ADD_NEW_INVITATION = 'ADD_NEW_INVITATION' // created new invitation
export const DELETE_INVITATION = 'DELETE_INVITATION' // when user ignores (declines) invitation
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION'

export const SAVE_MY_CONNECTIONS = 'SAVE_MY_CONNECTIONS'
export const DELETE_CONNECTION = 'DELETE_CONNECTION'
