export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION'
export const LOADING_CERTIFICATION = 'LOADING_CERTIFICATION'
export const SAVE_NEW_CERTIFICATION = 'SAVE_NEW_CERTIFICATION'
export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION'