export const CREATE_CHAT = 'CREATE_CHAT'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const GET_USER_CHATS = 'GET_USER_CHATS'
